language: perl
perl:
  - "5.14"
branches:
  only:
    - master
before_install:
  # modules
  - "cpanm DBD::mysql"
  - "cpanm DateTime"
  # install packages
  - "sudo apt-get update"
  - "sudo apt-get install lvm2 libconfig-inifiles-perl debhelper dpatch asciidoc xsltproc docbook-xsl"

install: true
